### ISSUE TITLE
Speed in kilometers per hour?

### ISSUE THREAD

**Issue by Mane55** [adafruit/Adafruit_CircuitPython_GPS#103]
There is only .speed_knots but I wish there were the SI unit meters/sec or more popular kilometers per hour in land traffic. Km/h is available from NMEA GPVTG message. I think its is only a line of code and enabling it in send command.

**Comment by snkYmkrct** [comment]
It was definitely more than one line of code, haha, since the VTG message was not being parsed at all. 
Anyway, here it is  https://github.com/adafruit/Adafruit_CircuitPython_GPS/pull/113 :smile_cat:

**Comment by Mane55** [comment]
Thanks for the solution.

BR
Mauno

LähetettyOutlook for Android<https://aka.ms/AAb9ysg>
________________________________
