### ISSUE TITLE
Typo in NMEA sentence checking

### ISSUE THREAD

**Issue by digixx** [adafruit/Adafruit_CircuitPython_GPS#44]
Hi,

in adafruit_gps.py, line 142
`if data_type in (
            b"GPGLL",
            b"GNGGL",
        ):`

GNGGL should be GNG**L**L?

Kind regards from Switzerland

**Comment by dherrada** [comment]
@digixx Yep, looks like you're right. Feel free to put in a PR fixing this, or, if youd prefer, I can.

**Comment by digixx** [comment]
@dherrada if you can do it, that would be fine.

**Comment by dherrada** [comment]
Fixed by #45
