### ISSUE TITLE
D+ D- on the adfruit GPS usb Breakout board.

### ISSUE THREAD

**Issue by akarsh1995** [adafruit/Adafruit_CircuitPython_GPS#48]
I'm quite new to these components.

I was able to connect this module to jetson nano through micro USB.

I would like to know what's the use of D+ and D- pin on the board ??

Couldn't find in the datasheet provided on the website.

**Comment by ladyada** [comment]
please contact the module manufacturer for assistance  they will drivers and datasheets for their part :)
