### ISSUE TITLE
The shortest NMEA sentence can be less than 32

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/Adafruit_CircuitPython_GPS#56]
Currently in `_read_sentence()` the code waits for at least 32 bytes before processing
```
def _read_sentence(self):
    # Only continue if we have at least 32 bytes in the input buffer
    if self.in_waiting < 32:
        return None
```

The shortest sentence I can find referenced in a datasheet is 15 bytes long:
`$PMTK501,2*28<CR><LF>`

I can find no definitive shortest sentence, but theoretically, there could be a sentence 11 bytes long:
`$XXXXX*ZZ<CR><LF>`
where the talker/sentence_type or proprietary_message is the message and needs no extra data.

**Comment by ladyada** [comment]
sure if ya like you can submit a PR to shorten it to 11 bytes, not that it isnt a 'minimum sentence' length thing, since usually multiple sentences get emitted at once.

**Comment by jposada202020** [comment]
@lesamouraipourpre now that changes were, was this fixed? let me know thanks :)
