### ISSUE TITLE
Usage of float causes timestamp_utc to be imprecise

### ISSUE THREAD

**Issue by mrdalgaard** [adafruit/Adafruit_CircuitPython_GPS#75]
NMEA timestamp is written as HHMMSS.sss, which is stored as float in the module.

Later it is converted to int which is inaccurate:
See example:
```
>> int(184105.000)
184104
```

This is then math'ed into the fields in time_struct.

Propose storing the NMEA sentence as string instead, and grabbing the sections of the sting directly.

**Comment by tannewt** [comment]
Note that it isn't the int conversion that is the problem. Storing it as a float is the issue. Try printing the float version back. My guess is that you'll get:

```
>> 184105.000
184104.0
```

**Comment by mrdalgaard** [comment]
> Note that it isn't the int conversion that is the problem. Storing it as a float is the issue. Try printing the float version back. My guess is that you'll get:
> 
> ```
> >> 184105.000
> 184104.0
> ```

I actually don't:

>>> 184105.000
184105.0
>>> int(184105.000)
184104

**Comment by tannewt** [comment]
:exploding_head:
