### ISSUE TITLE
Document parsed values stored as attributes

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_GPS#82]
`.latitude`, `.latitude_minutes`, `.timestamp_utc`, and all the other attributes set when parsing the sentence are not documented in the API doc. This should be fixed.

**Comment by awordforthat** [comment]
Picking this up at PyCon2023

**Comment by jerr0328** [comment]
This was fixed in #96? Is there something else to be done for this?

**Comment by awordforthat** [comment]
Yes, this can be closed.
