### ISSUE TITLE
Optional requirements missing

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_GPS#85]
Optional requirements used in the examples are missing from `optional_requirements.txt`.  Adding them there will better allow people to download them when wanting to use examples.

**Comment by tekktrik** [comment]
Looking at the examples, ``adafruit-circuitpython-sdcard`` needs to be added.

**Comment by tekktrik** [comment]
Do you want to submit a PR, @zeerakb1?

**Comment by zeerakb1** [comment]
yes

**Comment by tekktrik** [comment]
Sweet!  And just a heads up, the actual library name is `adafruit-circuitpython-sd`!
